### ISSUE TITLE
How best to contribute?

### ISSUE THREAD

**Issue by mattcasey** [TimRobinson1/notional#3]
Hi, thanks for sharing this module. I have a project where I want to be able to generate and maintain tables in Notion, and am extending this module a bit (for example, I added the ability to edit tables that are pages themselves which have BlockType: "collection_view_page"). Are you looking for PRs?

**Comment by TimRobinson1** [comment]
Hi @mattcasey!  Thanks so much for your interest in the repo, I'm glad it's been of use to you.

Sounds like a good addition 👍 

I've not had as much time to continue working on it personally as I would like.  Ideally, moving forwards I'd like to focus my time on improving the testing and drafting up some contributor/PR guidelines before I continue to add more functionality - so PRs on any functionality are definitely welcome!
I'd be very happy to review a PR with any improvements you might have for notional.

Would you be happy to open a PR for this? 🙂

**Comment by mattcasey** [comment]
OK thanks,

I am trying to get something out quickly (aren't we all!) but will send PRs as I have time. I'll break things up into separate PRs so it's easy to follow.

**Comment by mattcasey** [comment]
I sent a couple PRs and am closing this issue
