### ISSUE TITLE
Help with authentication - token maybe expiring?

### ISSUE THREAD

**Issue by mattcasey** [TimRobinson1/notional#9]
Sorry to bother about this, I don't think it's an issue directly related to your code. Twice now in the past few weeks, the /loadPageChunk endpoint starts returning an empty object, and it triggers an exception inside this lib when I'm calling `getTableIdsFromPage()` because `recordMap.block` is undefined. In both cases, the fix was to get a new API token. I can't confirm if the users had logged out or not -- the last person said they did not log out, so maybe Notion is expiring these tokens on their end? Does this sound familiar at all?

Thanks for any help!

**Comment by TimRobinson1** [comment]
>Sorry to bother about this

Not a bother at all 🙂 

I'm not certain what would cause a `token_v2` to become invalid or to start returning nothing - indeed I imagine logging out would do it but if they're not logging out then I'm not sure, there may well be an expiry but it's not something I've experienced before.

If you ever manage to reliably expire or invalidate your tokens, I'd be very interested to hear the cause.

Perhaps a worthwhile feature for this lib is to attempt to validate the token before using it? Whether such a thing is possible is something I'd have to find out!

**Comment by mattcasey** [comment]
ok thanks, I'm going to close for now since I can't reproduce. I asked in the Notion Discord and no one else had an idea either.  If/when it starts happening again, I'm going to try adding more logging around the HTTP response.
